export const ALL_TOOLS = [
  {
    id: "dashboard",
    name: "Dashboard",
    description: "Main overview and analytics hub",
    icon: "dashboard",
    route: "/dashboard",
    color: "#6366f1",
    gradient: "from-indigo-500 to-indigo-700",
    showOnDashboard: false,
  },
  {
    id: "call-detailing",
    name: "Call Detailing",
    description: "Track and analyze field calls",
    icon: "phone",
    route: "/tools/call-detailing",
    color: "#0ea5e9",
    gradient: "from-sky-500 to-sky-700",
    showOnDashboard: true,
  },
  {
    id: "sales-analyzer",
    name: "ATR Sales Analyzer",
    description: "Analyze ATR and sales performance",
    icon: "bar_chart",
    route: "/sales-analyzer",
    color: "#10b981",
    gradient: "from-emerald-500 to-emerald-700",
    showOnDashboard: true,
  },
  {
    id: "sales-forecast",
    name: "Sales Forecast",
    description: "Predict and plan future sales",
    icon: "trending_up",
    route: "/tools/sales-forecast",
    color: "#f59e0b",
    gradient: "from-amber-500 to-amber-700",
    showOnDashboard: true,
  },
  {
    id: "routing-analyzer",
    name: "Routing Analyzer",
    description: "Optimize field team routes",
    icon: "map",
    route: "/routing-analyzer",
    color: "#8b5cf6",
    gradient: "from-violet-500 to-violet-700",
    showOnDashboard: true,
  },
  {
    id: "links-library",
    name: "Library",
    description: "Quick access to resources and links",
    icon: "link",
    route: "/library",
    color: "#ec4899",
    gradient: "from-pink-500 to-pink-700",
    showOnDashboard: true,
  },
  {
    id: "admin-settings",
    name: "Admin Settings",
    description: "Manage users and system configuration",
    icon: "shield",
    route: "/admin-settings",
    color: "#6B7280",
    gradient: "from-slate-500 to-slate-700",
    showOnDashboard: true,
    adminOnly: true,
  },
  {
    id: "skill-zaty",
    name: "Skill-Zaty",
    description: "Training Center",
    icon: "school",
    route: "/skill-zaty",
    color: "#f97316",
    gradient: "from-orange-500 to-orange-700",
    showOnDashboard: true,
  },
];
