export const ALL_TOOLS = [
  {
    id: "dashboard",
    name: "Dashboard",
    description: "Main overview and analytics hub",
    icon: "⊞",
    route: "/dashboard",
    color: "#6366f1",
    gradient: "from-indigo-500 to-indigo-700",
    showOnDashboard: false,
  },
  {
    id: "call-detailing",
    name: "Call Detailing",
    description: "Track and analyze field calls",
    icon: "📞",
    route: "/tools/call-detailing",
    color: "#0ea5e9",
    gradient: "from-sky-500 to-sky-700",
    showOnDashboard: true,
  },
  {
    id: "sales-analyzer",
    name: "ATR Sales Analyzer",
    description: "Analyze ATR and sales performance",
    icon: "📊",
    route: "/tools/sales-analyzer",
    color: "#10b981",
    gradient: "from-emerald-500 to-emerald-700",
    showOnDashboard: true,
  },
  {
    id: "sales-forecast",
    name: "Sales Forecast",
    description: "Predict and plan future sales",
    icon: "📈",
    route: "/tools/sales-forecast",
    color: "#f59e0b",
    gradient: "from-amber-500 to-amber-700",
    showOnDashboard: true,
  },
  {
    id: "routing-analyzer",
    name: "Routing Analyzer",
    description: "Optimize field team routes",
    icon: "🗺️",
    route: "/routing-analyzer",
    color: "#8b5cf6",
    gradient: "from-violet-500 to-violet-700",
    showOnDashboard: true,
  },
  {
    id: "links-library",
    name: "Library",
    description: "Quick access to resources and links",
    icon: "🔗",
    route: "/links-library",
    color: "#ec4899",
    gradient: "from-pink-500 to-pink-700",
    showOnDashboard: true,
  },
  {
    id: "user-management",
    name: "User Management",
    description: "Manage users and permissions",
    icon: "⚙️",
    route: "/admin/users",
    color: "#64748b",
    gradient: "from-slate-500 to-slate-700",
    showOnDashboard: true,
    adminOnly: true,
  },
  {
    id: "skill-zaty",
    name: "Skill-Zaty",
    description: "Training Center",
    icon: "🎓",
    route: "/skill-zaty",
    color: "#f97316",
    gradient: "from-orange-500 to-orange-700",
    showOnDashboard: true,
  },
];
